### ISSUE TITLE
Develop script to ensure consistency of Github PR template

### ISSUE THREAD

**Issue by jaypipes** [aws-controllers-k8s/community#848] opened 2021-06-28 15:29 UTC
As we've added more repositories to the aws-controllers-k8s Github organization, there has been some drift in the Github PR template (.github/PULL_REQUEST_TEMPLATE.md) used in the various repositories.

We should develop a script (maybe in test-infra or ack-dev repositories) to ensure the consistency of this PR template.

**Comment by RedbackThomson** [comment] 2021-08-18 20:28
Duplicate of https://github.com/aws-controllers-k8s/community/issues/887 .

**Closed by RedbackThomson** 2021-08-18 20:28 UTC
Labels: enhancement, good first issue, help wanted, project-management, priority/backlog
