### ISSUE TITLE
Document ACK service controller upgrade (and downgrade)

### ISSUE THREAD

**Issue by kumargauravsharma** [aws-controllers-k8s/community#433] opened 2020-10-23 01:29 UTC
**Is your feature request related to a problem?**
This feature request is to have a document that will provide details on how to rollback or roll forward ACK service controllers on K8s cluster.

Consider following scenarios:
1. A K8s cluster with Custom resources already created using CRD from older version of ACK service controller. What steps should be followed to deploy new ACK controller version (with updated CRDs) to existing cluster so that existing Custom Resources start getting managed by new controller.
2. What steps should be followed to deploy older ACK controller version (or revert to previous version)

**Describe the solution you'd like**
Documentation with details on how to how to rollback or roll forward ACK service controllers on K8s cluster.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by jaypipes** [comment] 2022-11-11 17:49
Closing this out as a duplicate of #1432 (and yes, I know this one is earlier than that one...)

**Closed by jaypipes** 2022-11-11 17:49 UTC
Labels: enhancement, multi-versioning
