### ISSUE TITLE
IAM Controller v0.0.5 Doesn't Update Policies

### ISSUE THREAD

**Issue by samruthr** [aws-controllers-k8s/community#1177] opened 2022-02-11 20:39 UTC
**Describe the bug**
Updating an existing policy spec doesn't update the IAM policy itself. We no longer see the "not implemented" reconciliation error, however a new policy version isn't created nor does the policy change. I do see that the spec has been updated successfully:
`
status:
  ackResourceMetadata:
    arn: 'arn:aws:iam::<ACCTID>:policy/test'
    ownerAccountID: '<ACCTID>'
  attachmentCount: 21
  conditions:
    - lastTransitionTime: '2022-02-11T18:50:29Z'
      status: 'True'
      type: ACK.ResourceSynced
    - lastTransitionTime: '2022-02-11T18:50:29Z'
      message: Late initialization successful
      reason: Late initialization successful
      status: 'True'
      type: ACK.LateInitialized
  createDate: '2022-02-04T22:07:13Z'
  defaultVersionID: v1
  isAttachable: true
  permissionsBoundaryUsageCount: 0
  policyID: <ID>
  updateDate: '2022-02-04T22:07:13Z'
`

**Steps to reproduce**
- Create an IAM policy
- Update the policy spec
- Apply change to EKS
- Check IAM policy to reflect the change

**Expected outcome**
The IAM policy should update reflecting the change made to the policy spec.

**Environment**
* EKS version 1.18
* AWS service targeted: IAM

**Comment by A-Hilaly** [comment] 2022-02-14 01:51
Thanks for opening this issue @samruthr, the iam-controller still doesn't support updates for all the fields. It only supports tags updates for the moment.

**Comment by jaypipes** [comment] 2022-02-14 15:02
Closing as this is a duplicate of #1124

**Closed by jaypipes** 2022-02-14 15:02 UTC
Labels: enhancement, IAM
