### ISSUE TITLE
ec2/load balancer service controller

### ISSUE THREAD

**Issue by tomitesh** [aws-controllers-k8s/community#1813] opened 2023-06-01 08:53 UTC
## New ACK Service Controller
We utilize GitOps to deploy all assets by leveraging the aws-controllers-k8s framework. I did not find any controller which creates ALB. The closest match i found is [this one](https://gallery.ecr.aws/eks/aws-load-balancer-controller) which is not maintaned by your team.

a new controller to create AWS Load Balancer or add load balancer features in existing EC2 controller

Support for [service name]
EC2 (ALB and NLB)

### List of API resources
List the API resources in order of importance to you:

1) ALB

kindly suggest any controller exists for creating ALB. if not is it possible to create new or amend existing EC2 controller to add ALB features?

**Comment by RedbackThomson** [comment] 2023-06-01 18:05
I believe this is a duplicate of https://github.com/aws-controllers-k8s/community/issues/487

**Closed by RedbackThomson** 2023-06-01 18:05 UTC

**Comment by tomitesh** [comment] 2023-06-06 10:23
Thanks for your reply.

are you going to support creation of load balancers (ALB/NLB) without being tied to k8s ingress? i just want to create ALB directly.

**Comment by jaypipes** [comment] 2023-06-06 13:17
> @RedbackThomson Thanks for your reply.
> 
> are you going to support creation of load balancers (ALB/NLB) without being tied to k8s ingress? i just want to create ALB directly.

This is unlikely to happen any time soon, unfortunately. Just no resources to work on this :(
