### ISSUE TITLE
Error while updating Dynamodb with GSI

### ISSUE THREAD

**Issue by riddhi2910** [aws-controllers-k8s/community#1920] opened 2023-10-05 16:01 UTC
**Describe the bug**
We upgraded the dynamodb controller to 1.2.3. We did that because in our previous version, when we updated the existing table with the globalSecondaryIndex  . The controller was not able to create the GSI.
We created GSI manually on the AWS, after that added the configs for GSI on the ACK dyanmodb object.
We see errors like this afterwards
We think, the controller is not able to update/patch the changes. Creating a new table with GSI works fine.
  conditions:
  - message: Table in 'UPDATING' state, cannot be modified or deleted
    status: "True"
    type: ACK.Recoverable
  - lastTransitionTime: "2023-10-04T20:44:04Z"
    message: Unable to determine if desired resource state matches latest observed
      state
    reason: Table in 'UPDATING' state, cannot be modified or deleted
**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* Kubernetes version 
* Using EKS (yes/no), if so version? Yes
* AWS service targeted (S3, RDS, etc.) Dynamodb

**Comment by a-hilaly** [comment] 2023-10-10 15:46
We believe this might be fixed with https://github.com/aws-controllers-k8s/dynamodb-controller/pull/73

**Comment by riddhi2910** [comment] 2023-10-10 18:41
@a-hilaly Thanks, When will you be able to roll this out ?

**Comment by riddhi2910** [comment] 2023-11-06 19:23
@a-hilaly Can I get an update on this?

**Comment by Julian-Chu** [comment] 2023-11-07 21:36
@riddhi2910  
could you  please provide your yaml?

**Comment by joaquinservetto** [comment] 2023-11-09 17:26
I'll be working on this one, @a-hilaly could you please assign the issue to me?

**Comment by a-hilaly** [comment] 2023-11-13 23:27
@joaquinservetto Assigned to you - thank you! If you can, please provide more information on the provided spec - so that we have a good understand what's the issue is really about.

**Comment by joaquinservetto** [comment] 2023-11-17 14:33
Hi @a-hilaly, I'll share the specs that I used to reproduce the issue, this only happens on the update process so you need to apply this manifests in order to face the error.

**Comment by joaquinservetto** [comment] 2023-11-17 14:33
Hi @a-hilaly, I'll share the specs that I used to reproduce the issue, this only happens on the update process so you need to apply this manifests in order to face the error.

**Comment by joaquinservetto** [comment] 2023-11-17 14:43
Hi @a-hilaly, I'll share the specs that I used to reproduce the issue, this only happens in the update process so you need to apply these manifests in the following order to face the error.
```
spec:
  attributeDefinitions:
  - attributeName: externalId
    attributeType: S
  - attributeName: test-numbers
    attributeType: "N"
  billingMode: PAY_PER_REQUEST
  continuousBackups:
    pointInTimeRecoveryEnabled: false
  keySchema:
  - attributeName: externalId
    keyType: HASH
  - attributeName: test-numbers
    keyType: RANGE
  tableClass: STANDARD
  tableName: test-0008-dev


spec:
  attributeDefinitions:
  - attributeName: externalId
    attributeType: S
  - attributeName: test-numbers
    attributeType: "N"
  globalSecondaryIndexes:
    - indexName: test-gsi
      projection:
        projectionType: ALL
      keySchema:
      - attributeName: test-numbers
        keyType: HASH
      - attributeName: externalId
        keyType: RANGE
  billingMode: PAY_PER_REQUEST
  continuousBackups:
    pointInTimeRecoveryEnabled: false
  keySchema:
  - attributeName: externalId
    keyType: HASH
  - attributeName: test-numbers
    keyType: RANGE
  tableClass: STANDARD
  tableName: test-0008-dev

**Comment by joaquinservetto** [comment] 2023-11-17 15:11
@a-hilaly there were two bugs related to this issue, one of them was resolved by @Julian-Chu in this [PR](https://github.com/aws-controllers-k8s/dynamodb-controller/pull/85). I raised another one for an error that only happened when creating a gsi using previously defined attributes.

**Comment by a-hilaly** [comment] 2023-11-23 04:11
@joaquinservetto Thanks for your contribution! Can you send a release PR? basically run `RELEASE_VERSION=v1.2.5 ./scripts/build-controller-release.sh dynamodb` and send a PR of the generated artifact

**Comment by a-hilaly** [comment] 2023-11-23 15:57
@joaquinservetto Maybe before making a release let's add some e2e tests to make sure that the controller is being able to make the updates properly

**Closed** 2024-06-04 07:26 UTC
Labels: kind/bug, service/dynamodb
