### ISSUE TITLE
can't create buckets with policy

### ISSUE THREAD

**Issue by masterkain** [aws-controllers-k8s/community#1796] opened 2023-05-05 09:19 UTC
I'm using flux 2 (gitops)

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ack-s3-controller
spec:
  releaseName: ack-s3-controller
  chart:
    spec:
      chart: s3-chart
      version: "v1.0.3"
      ...
```

```yaml
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: staging-bucket-it
spec:
  name: staging-bucket-it
  acl: private
  versioning:
    status: Enabled
  ownershipControls:
    rules:
      - objectOwnership: BucketOwnerPreferred
  policy: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "AllowPublicRead",
          "Effect": "Allow",
          "Principal": {
            "AWS": "*"
          },
          "Action": "s3:GetObject",
          "Resource": "arn:aws:s3:::staging-bucket-it/*"
        }
      ]
    }
  cors:
    corsRules:
      - allowedHeaders:
          - "Authorization"
        allowedMethods:
          - "GET"
        allowedOrigins:
          - "https://mydomain.com"
        maxAgeSeconds: 3000
```

The problem is that the AWS S3 controller fails with a 403 Forbidden error when it tries to perform a policy update right after creating the bucket. The bucket gets created, but without the policy, CORS settings, or the `publicAccessBlock` setting, if present. I've tried various combinations of adding and removing settings, but I still can't get the bucket to work properly with publicly accessible content on the first synchronization attempt.

I also tried setting the `publicAccessBlock` to allow public access, but that doesn't work either. The controller attempts to set the policy before applying the publicAccessBlock setting, causing the synchronization to fail.

The only way I've been able to get it to work is by manually going into the AWS S3 console, navigating to the Permissions tab of the "created-but-not-configured" bucket, editing the "Block public access (bucket settings)" settings, ensuring that no checkboxes are selected, and then saving the changes. After that, the synchronization works as expected.

I've raised this issue on GitHub because I'd like to know if there's a way to set up the bucket with publicly accessible content using a manifest without having to resort to manual intervention in the AWS console.

**Comment by RedbackThomson** [comment] 2023-05-15 23:15
I was able to reproduce the error, and then by syncing the public access configuration before trying to sync the policy I found that it works. This is the modified version of the manifest that I ran (note `publicAccessBlock` - I'm not sure if they're necessary, but I added them to be sure I had permissions):
```yaml
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: issue-1796
spec:
  name: issue-1796
  acl: private
  versioning:
    status: Enabled
  publicAccessBlock:
    blockPublicPolicy: false
    blockPublicACLs: true
    ignorePublicACLs: true
  ownershipControls:
    rules:
      - objectOwnership: BucketOwnerPreferred
  policy: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "AllowPublicRead",
          "Effect": "Allow",
          "Principal": {
            "AWS": "*"
          },
          "Action": "s3:GetObject",
          "Resource": "arn:aws:s3:::issue-1796/*"
        }
      ]
    }
  cors:
    corsRules:
      - allowedHeaders:
          - "Authorization"
        allowedMethods:
          - "GET"
        allowedOrigins:
          - "https://mydomain.com"
        maxAgeSeconds: 3000
```

The bug fix for this situation is linked above

**Comment by RedbackThomson** [comment] 2023-05-16 18:39
https://github.com/aws-controllers-k8s/s3-controller/releases/tag/v1.0.4 was just released, which contains this fix. Please try it out and let me know if it works.

**Comment by masterkain** [comment] 2023-05-17 12:01
my system still can't see 1.0.4

```
chart pull error: failed to download chart for remote reference: failed to get 'oci://public.ecr.aws/aws-controllers-k8s/s3-chart:v1.0.4': public.ecr.aws/aws-controllers-k8s/s3-chart:v1.0.4: not found
```

**Comment by masterkain** [comment] 2023-05-17 13:19
I'm not sure this is intended https://github.com/aws-controllers-k8s/s3-controller/commit/e0addd656d76730fbf0eac428e29f4520b0525ba

but it removed the "v" before the helm chart versions, so I had to set `version: "1.0.4"` instead of `version: "v1.0.4"` to find the new version.

anyway I'm testing the changes, will report back.

**Comment by RedbackThomson** [comment] 2023-05-18 16:10
> I'm not sure this is intended [aws-controllers-k8s/s3-controller@e0addd6](https://github.com/aws-controllers-k8s/s3-controller/commit/e0addd656d76730fbf0eac428e29f4520b0525ba)
> 
> but it removed the "v" before the helm chart versions, so I had to set `version: "1.0.4"` instead of `version: "v1.0.4"` to find the new version.

Yes, we recently changed the versioning schema to remove the v. Please see the community issue - https://github.com/aws-controllers-k8s/community/issues/1802

**Comment by RedbackThomson** [comment] 2023-05-18 16:14
> s3 bucket to allow for direct changes without passing through an AdoptedResource

The resources have to be actively managed by the S3 controller for you to make changes to them. We can't just edit a single field individually. 

> so I guess the original problem described in the issue should be solved

Since this original issue has been solved, I'm going to close this GH issue. I'm happy to talk about the issue of S3 bucket adoption, if you want to open a separate GH issue for that - so we can track it separately.

**Closed by RedbackThomson** 2023-05-18 16:14 UTC
Labels: kind/bug, priority/important-soon, service/s3
