### ISSUE TITLE
ElastiCache controller error: invalid: status.ackResourceMetadata.region: Required value

### ISSUE THREAD

**Issue by riddhi2910** [aws-controllers-k8s/community#1805] opened 2023-05-18 20:14 UTC
**Describe the bug**
We have upgraded the Elasticache Controller Version v0.0.23 and now the existing resources getting below errors

``` 2023-05-17T07:11:49.837Z	ERROR	Reconciler error	{"controller": "replicationgroup", "controllerGroup": "elasticache.services.k8s.aws", "controllerKind": "ReplicationGroup", "ReplicationGroup": {"name":"ndi","namespace":"preview"}, "namespace": "preview", "name": "ndi", "reconcileID": "a43187e4-4af4-4730-955f-cebb4f97f987", "error": "ReplicationGroup.elasticache.services.k8s.aws \"ndi\" is invalid: status.ackResourceMetadata.region: Required value"} ```

and if we manually update the existing resporce via `kubectl edit --subresource=status` we are getting  `* spec.description: Required value`

**Steps to reproduce**

Upgrade the controller and try the version change

**Expected outcome**
It should able to update the existing resources 

**Environment**

* Kubernetes version 1.24
* Using EKS (yes/no), if so version? Yes
* AWS service targeted (S3, RDS, etc.) Redis

**Comment by RedbackThomson** [comment] 2023-06-01 18:15
Weirdly I don't see a required annotation on the region field in the Go code: https://github.com/aws-controllers-k8s/runtime/blob/main/apis/core/v1alpha1/resource_metadata.go#L33-L34

But I do see it set to required in the CRD: https://github.com/aws-controllers-k8s/elasticache-controller/blob/main/config/crd/bases/elasticache.services.k8s.aws_replicationgroups.yaml#L431-L433

It's possible that the version of the Elasticache controller you were using previously was particularly old, or faulty, and didn't add the required fields to the status originally. If you create a new `ReplicationGroup` resource, with the newest version of the controller, do you see these fields are populated?

**Comment by eadasiak** [comment] 2024-10-10 16:49
It turns out we were missing the AWS region annotations in several places, and the controller was unable to determine a value for it.

The resource lacked a specific region annotation, the namespace also wasn't annotated with a region, and the region setting in the helm chart wasn't configured.

@a-hilaly - should we go ahead and close this as expected behavior, then?

**Comment by a-hilaly** [comment] 2024-10-10 20:09
Thank you for debugging this @eadasiak ! Yes we can close this :) 

/close

**Closed by a-hilaly** 2024-10-10 20:09 UTC
Labels: priority/awaiting-more-evidence, service/elasticache
