### ISSUE TITLE
[SageMaker] TrainingJobs not bubbling up errors properly  

### ISSUE THREAD

**Issue by akartsky** [aws-controllers-k8s/community#1012] opened 2021-10-07 19:33 UTC
**Describe the bug**
If you submit a TrainingJob with a name which already exists in SageMaker then the controller reconciles (and stops) without bubbling up any error to the user.

This might be happening with other resources too 

**Steps to reproduce**
Submit a TrainingJob with a name which already exists in SageMaker

**Expected outcome**
Show the error in `kubectl describe trainingjob`

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 
* AWS service targeted (S3, RDS, etc.)

**Comment by jaypipes** [comment] 2021-10-07 19:38
Hi @akartsky! This is actually a duplicate of #1002. Closing this one out and poking @RedbackThomson :)

**Closed as completed by jaypipes** 2021-10-07 19:38 UTC
Labels: kind/bug
