### ISSUE TITLE
Adopt already generated resource

### ISSUE THREAD

**Issue by nicraMarcin** [aws-controllers-k8s/community#2165] opened 2024-09-06 17:06 UTC
Hi, 
We are going to switch from Terraform to AWS ACK Operators.
[AdoptedResource](https://pkg.go.dev/github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1#AdoptedResource) is very helpful in migration but we are luck of adopting created manifests.

When adopter creates manifest, for example bucket, operator starts managing it and we can delete AdoptedResource and use generated Bucket moving it to code removing .status for future use on other cluster and add it to stack of others resources. Sometimes we would like to delete manifest not deleting resource on AWS, for example moving manifests to another cluster. On this new cluster we would like just adopt resources from Bucket manifest which are already created. But when we deploy Bucket manifest it says that resource exist and we need to use AdoptedResource but there is another "but":
 - when we deploy AdoptedResource without bucket manifest resource is adopted but we must start deploy from the beninig 
 - when we deploy AdoptedResource and Bucket manifest at the same time resource isn't adopted because exists.
 
Is it any possibility to annotate manifest to be adopted when such resource exists or create new when there is no such resource?

**Comment by gecube** [comment] 2024-09-09 08:14
Hi! Totally agree.
But is this issue the duplicate of #1381 or no?

**Comment by nicraMarcin** [comment] 2024-09-09 19:34
Hi, 
It could be duplicated 👍 I didn't notice that.

**Comment by a-hilaly** [comment] 2024-09-26 00:29
Thank you folks, let's close this one and track this feature in https://github.com/aws-controllers-k8s/community/issues/1381 :) 
This is currently in the backlog of the ACK team and will be implemented before reinvent.

**Closed by a-hilaly** 2024-09-26 00:29 UTC
