### ISSUE TITLE
DBCluster stucks on "Cluster cannot be deleted, it still contains DB instances in non-deleting state"

### ISSUE THREAD

**Issue by franroa** [aws-controllers-k8s/community#1151] opened 2022-01-31 15:49 UTC
**Describe the bug**
When a DBCluster is removed together with the corresponding DBInstances and DBSubnetGroup there is an error because kubernetes tries to remove the cluster before the instances are removed, then when the instances are finally removed, the cluster does not reconcile the state and stucks on "Cluster cannot be deleted, it still contains DB instances in non-deleting state". There are no instances left, though, and consequently, the subnet groups are also not deleted

**Steps to reproduce**
Remove the resources in this order: DBSubnetGroup, DBCluster, DBInstances

**Expected outcome**
I would have expected the state to be automatically reconcilied 

**Environment**

* Kubernetes version (EKS 1.20)
* Using EKS (yes/no), if so version?  -> yes, 1.20
* AWS service targeted (S3, RDS, etc.) -> RDS

**Comment by vijtrip2** [comment] 2022-01-31 16:56
Hi @franroa , thanks for reaching out. If you have this scenario reproducible, can you please `kubectl describe` the DBCluster resource and paste in the comment here(trimming any sensitive fields)

I am interested to see what the `Status` looks like and does the reconciliation for `DBCluster` stop due to any `Status.Conditions` . Thanks!

**Comment by franroa** [comment] 2022-02-01 08:55
Hi, thank you for the quick reply. This is the status of my resources.

`Status:
  Ack Resource Metadata:
    Arn:                   arn:aws:rds:eu-west-1:xxxxxxxxxxxxxxxxxxxxxxx
    Owner Account ID:      xxxxxxxxxxxxxx
  Activity Stream Status:  stopped
  Allocated Storage:       1
  Cluster Create Time:     2022-01-31T15:12:36Z
  Conditions:
    Last Transition Time:  2022-01-31T15:29:39Z
    Status:                True
    Type:                  ACK.ResourceSynced
    Message:               InvalidDBClusterStateFault: Cluster cannot be deleted, it still contains DB instances in non-deleting state.
                           status code: 400, request id: 9624c6fa-1c78-4cfb-a70e-148dd5a65d1d
    Status:                True
    Type:                  ACK.Terminal
  Cross Account Clone:     false
  Db Cluster Members:
    Db Cluster Parameter Group Status:  in-sync
    Db Instance Identifier:             xxxxxxxxxxxxxxxxx
    Is Cluster Writer:                  false
    Promotion Tier:                     1
    Db Cluster Parameter Group Status:  in-sync
    Db Instance Identifier:             xxxxxxxxxxxxxx
    Is Cluster Writer:                  true
    Promotion Tier:                     1
  Db Cluster Parameter Group:           defaultxxxxxxxxxxxxx
  Db Cluster Resource ID:               cluster-xxxxxx
  Db Subnet Group:                      franxxxxxxxxxxxxxxx
  Earliest Restorable Time:             2022-01-31T15:13:23Z
  Endpoint:                             franxxxxxxxxxxxxxxx
  Hosted Zone ID:                       Zxxxxxxxxxxx
  Http Endpoint Enabled:                false
  Iam Database Authentication Enabled:  false
  Latest Restorable Time:               2022-01-31T15:28:47Z
  Multi AZ:                             true
  Reader Endpoint:                      franxxxxxxxxxxxx
  Status:                               available
  Vpc Security Groups:
    Status:                 active
    Vpc Security Group ID:  sg-xxxxxxxxxxxxxxx
Events:                     <none>
`

**Comment by vijtrip2** [comment] 2022-02-01 17:48
Thanks @franroa , it seems like cluster is placed in Terminal State when it encounters this error, hence does not reconcile after that.
Yesterday a new release of rds controller was published, which handles similar error during Update. I will take a look at this soon and attempt to fix this.

**Comment by franroa** [comment] 2022-02-02 08:50
thank you so much @vijtrip2

**Comment by vijtrip2** [comment] 2022-02-04 19:28
This should get fixed in the next release of rds controller. Most probably we will do another release for controllers next week.

**Closed** 2022-02-11 17:40 UTC
Labels: bug, priority/important-soon
