### ISSUE TITLE
RDS Changes to instanceClass stuck in loop

### ISSUE THREAD

**Issue by MartinHell** [aws-controllers-k8s/community#1773] opened 2023-04-14 14:42 UTC
**Describe the bug**
When updating the dbInstanceClass of an RDS instance the RDS ACK controller gets stuck in a loop redeploying the two different instanceClasses. First it changes the RDS instance to the new class then changes it back to the old class. This goes on forever

**Steps to reproduce**
Deploy a dbinstance with the dbInstanceClass db.t3.micro and then change the dbInstanceClass to db.m5.large. The instance will change between the two classes indefinitely.

**Expected outcome**
The instance should be updated to the new dbInstanceClass and stay on that class

**Environment**

* v1.25.8
* Yes v1.25.8-eks-ec5523e
* RDS

**Comment by jaypipes** [comment] 2023-05-10 19:17
I believe I have discovered the cause of this cursed behaviour. The Output shape for Update operations on RDS resources contains fields that have the previously set value (and those fields are named the same as the field in question .. e.g. dbInstanceClass). There is a separate sub struct called PendingModifiedValues in the Output shape that contains the new values for those fields. The SetOutput Go code is matching the fields that contain the previous values, setting the Spec.DBInstanceClass for example to that previous value. Thus the flopping behaviour. The fix is to set the Spec field to the value in PendingModifiedValues -- or, frankly, just don't set the Spec fields to anything in the Output shape from Update operations.

Working on a patch now.

**Comment by jljaco** [comment] 2023-05-17 17:32
@jaypipes is there any remaining work to be done on this issue since https://github.com/aws-controllers-k8s/rds-controller/pull/151 was merged?  can this be closed?

**Comment by jaypipes** [comment] 2023-05-17 17:50
> @jaypipes is there any remaining work to be done on this issue since [aws-controllers-k8s/rds-controller#151](https://github.com/aws-controllers-k8s/rds-controller/pull/151) was merged? can this be closed?

Nope. Closing out.

**Closed by jaypipes** 2023-05-17 17:50 UTC
Labels: kind/bug, priority/critical-urgent, service/rds
