### ISSUE TITLE
Resource References for RDS CRDs

### ISSUE THREAD

**Issue by jkatz** [aws-controllers-k8s/community#1378] opened 2022-07-01 00:48 UTC
**Is your feature request related to a problem?**

To support GitOps workflows, we need to add resource references to the RDS CRDs. This will allow for resources to be reconciled at the correct time when other resources are available.

**Describe the solution you'd like**

We should create the following resource references on each CRD. (The non-referenced field is listed in parentheses).

* `DBCluster`
  * `dbClusterParameterGroupRef` => `DBClusterParameterGroup` (`dbClusterParameterGroupName`)
  * `dbSubnetGroupRef` => `DBSubnetGroup` (`dbSubnetGroupName`)
  * `[]vpcSecurityGroupRef` => `[]SecurityGroup` (in the EC2 controller) (`vpcSecurityGroupIDs`)
* `DBCluster`
  * `dbParameterGroupRef` => `DBParameterGroup` (`dbClusterParameterGroupName`)
  * `dbSubnetGroupRef` => `DBSubnetGroup` (`dbSubnetGroupName`)
  * `[]vpcSecurityGroupRef` => `[]SecurityGroup` (in the EC2 controller) (`vpcSecurityGroupIDs`)

**Describe alternatives you've considered**

The current solution is to create resources outside of Kubernetes (e.g. with the AWS CLI) and transform those values into manifests that can be used by ACK.

**Comment by brucegucode** [comment] 2022-07-06 23:27
if i understand it correctly, it's to allow RDS CRD like DBCluster or DBInstance to refer RDS other CRD like DBParamGroup/ DBClusterParamGroup or EC2 CRD like SecurityGroup ? 
similar to https://github.com/aws-controllers-k8s/eks-controller/blob/main/generator.yaml#L5

**Comment by brucegucode** [comment] 2022-07-07 18:19
I'm thinking about this change https://github.com/brucegucode/rds-controller/blob/issue-1378/generator.yaml#L110-L122 , but I'm not sure how to test it. The test process I'm thinking is like 
1. create db instance with a specified db param group reference which point to a non-existing db param group.
2. create db param group from Spec , so it's available in k8s and then created in rds 
3. verify db instance in step 1 get created as well. 
But the issue is if we create param group in k8s, it will be available in rds too. How to verify rds instance get created because of object created in k8s or because of rds param group is created ?

**Comment by RedbackThomson** [comment] 2022-07-07 18:36
We have created tests for other resources that use references. See https://github.com/aws-controllers-k8s/apigatewayv2-controller/blob/main/test/e2e/tests/test_references.py

Essentially, we apply a number of resources in the opposite order of their dependencies (that is we create the one that has no references to anything else at the end) and check that, after they've all been applied, they reach Synced

**Comment by brucegucode** [comment] 2022-07-08 17:20
code merged, going to close this one. i plan to add e2e test for it, but need do https://github.com/aws-controllers-k8s/community/issues/1325 first

**Closed** 2022-07-08 17:20 UTC
Labels: enhancement, RDS, priority/important-soon

**Comment by jkatz** [comment] 2022-07-09 00:42
🎉

**Comment by cdaveaws** [comment] 2022-07-11 13:41
👍
