### ISSUE TITLE
End-to-end (e2e) tests for the ACK service controller for EKS fails to clean up VPC resources that were created during test bootstrapping.

### ISSUE THREAD

**Issue by nonoy-suguitan** [aws-controllers-k8s/community#1509] opened 2022-10-17 15:48 UTC
**Describe the bug**
As part of the e2e testing for the EKS, AWS VPC resources are generated during the bootstrapping step.
The last step of testing, which attempts to clean up the generated resources, fails due to dependency errors:

> [INFO] Tests succeeded!
[INFO] Running test cleanup ...
INFO:root:🧹 Cleaning up resources ...
INFO:root:Attempting cleanup Role
INFO:root:Successfully cleaned up Role
INFO:root:Attempting cleanup Role
INFO:root:Successfully cleaned up Role
INFO:root:Attempting cleanup Role
INFO:root:Successfully cleaned up Role
INFO:root:Attempting cleanup VPC
INFO:root:Attempting cleanup Subnets
INFO:root:Attempting cleanup RouteTable
INFO:root:Successfully cleaned up RouteTable
INFO:root:Successfully cleaned up Subnets
INFO:root:Attempting cleanup Subnets
ERROR:root:Exception while cleaning up Subnets
ERROR:root:An error occurred (DependencyViolation) when calling the DeleteSubnet operation: The subnet 'subnet-######' has dependencies and cannot be deleted.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/acktest/bootstrapping/__init__.py", line 152, in _cleanup_resources
    resource.cleanup()
  File "/usr/local/lib/python3.8/site-packages/acktest/bootstrapping/vpc.py", line 140, in cleanup
    self.ec2_client.delete_subnet(SubnetId=subnet)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 708, in _make_api_call
    raise error_class(parsed_response, operation_name)
...
...
ERROR:root:🚫 Exceeded maximum retries (3) for cleaning up Subnets
ERROR:root:Possibly dangling resource (Subnets): {'vpc_id': 'vpc-######', 'cidr_blocks': ['10.0.0.0/24', '10.0.1.0/24'], 'is_public': True, 'num_subnets': 2, 'map_public_ip': True, 'route_table': {'vpc_id': 'vpc-######', 'is_public': True, 'internet_gateway': {'vpc_id': 'vpc-######', 'internet_gateway_id': 'igw-######'}, 'route_table_id': 'rtb-######'}, 'subnet_ids': ['subnet-######', 'subnet-######']}
ERROR:root:Exception while cleaning up VPC
ERROR:root:An error occurred (DependencyViolation) when calling the DeleteVpc operation: The vpc 'vpc-######' has dependencies and cannot be deleted.

**Steps to reproduce**
Run e2e testing for the AWS EKS service, as described on https://aws-controllers-k8s.github.io/community/docs/contributor-docs/testing/

**Expected outcome**
The VPC resources should be cleaned up in an order that avoids dependency errors.

**Environment**

* Kubernetes version: 1.22.9
* Using EKS (yes/no), if so version? No, the tests creates a KIND cluster, which is the default https://github.com/aws-controllers-k8s/test-infra/blob/main/test_config.example.yaml#L5
* AWS service targeted (S3, RDS, etc.): EKS, VPC

**Comment by A-Hilaly** [comment] 2022-10-17 22:43
Hi @nonoy-suguitan , thank you for reporting this. It's a little bit surprising because we have a lot of other controllers who are using the same bootstrapping constructs.. and do not experience any clean up errors. Were you able to reproduce these errors more than one time?

**Comment by nonoy-suguitan** [comment] 2022-10-17 23:11
Hi @A-Hilaly,
Yes, I've execute the EKS e2e testing multiple times, and they all produced the same errors.
However, the manual process of cleaning up the VPC resources using the AWS management console differs.
In one case, I was able to clean up VPC resources from the VPCs page > Actions > Delete VPC.
In another case, the above actions fails due to an ENI resource still attached to one of the subnets. I was able to get around that by deleting the ENI first, then the rest of the VPC resources.

In contrast, I've ran e2e testing for the Amazon S3 and AWS KMS and those were able to successfully cleanup resources.

Please let me know if you need any other details.

**Comment by A-Hilaly** [comment] 2022-10-18 00:27
Thank you @nonoy-suguitan , looks like this is something we also have in our prow job for eks-controller e2e tests https://prow.ack.aws.dev/view/s3/ack-prow-logs/pr-logs/pull/aws-controllers-k8s_eks-controller/51/eks-kind-e2e/1569459373091065856

**Comment by A-Hilaly** [comment] 2022-10-19 14:12
Looks like ec2 e2e tests are also impacted. Thank you for pointing out this @nonoy-suguitan

**Comment by jljaco** [comment] 2023-06-16 14:34
All VPC resources should now be cleaned up properly upon e2e test termination.

**Comment by jljaco** [comment] 2023-06-16 16:25
Problem still exists, despite tests "passing": https://prow.ack.aws.dev/log?job=eks-kind-e2e&id=1669729752019111936

**Comment by gecube** [comment] 2023-07-24 08:00
The problem is still reproducible.

1. create the VPC resources with manifests
2. comment out all resourced in the manifests and apply to gitops repo or remove the resources with kubectl.
3. The VPC remains with the routing tables and controller complains:

```
2023-07-24T07:57:27.346Z	ERROR	Reconciler error	{"controller": "elasticipaddress", "controllerGroup": "ec2.services.k8s.aws", "controllerKind": "ElasticIPAddress", "ElasticIPAddress": {"name":"natgateway-eu-west-2a-ip","namespace":"infra-production"}, "namespace": "infra-production", "name": "natgateway-eu-west-2a-ip", "reconcileID": "a2a9f629-98bc-4877-b940-6be2d11ef361", "error": "AuthFailure: You do not have permission to access the specified resource.\n\tstatus code: 400, request id: 08c35249-98ec-4816-8c67-eef5d13726e0"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235
2023-07-24T07:57:57.657Z	INFO	ackrt	deleted resource	{"account": "966321756598", "role": "arn:aws:iam::966321756598:role/ack-ec2-controller-tooling", "region": "eu-west-2", "kind": "InternetGateway", "namespace": "infra-production", "name": "production", "generation": 3}
2023-07-24T07:57:58.177Z	ERROR	Reconciler error	{"controller": "vpc", "controllerGroup": "ec2.services.k8s.aws", "controllerKind": "VPC", "VPC": {"name":"production","namespace":"infra-production"}, "namespace": "infra-production", "name": "production", "reconcileID": "1f2f2fc6-a0cc-452e-b2af-19e2a1650398", "error": "DependencyViolation: The vpc 'vpc-0444e36b17c4a89b5' has dependencies and cannot be deleted.\n\tstatus code: 400, request id: 54efefb1-08e1-48f9-967e-f841978e701d"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235
2023-07-24T07:58:01.328Z	ERROR	Reconciler error	{"controller": "routetable", "controllerGroup": "ec2.services.k8s.aws", "controllerKind": "RouteTable", "RouteTable": {"name":"production-public-route-table","namespace":"infra-production"}, "namespace": "infra-production", "name": "production-public-route-table", "reconcileID": "49f90220-220d-4087-b5d6-6f285e2571ae", "error": "DependencyViolation: The routeTable 'rtb-0b2f07b10829c0c62' has dependencies and cannot be deleted.\n\tstatus code: 400, request id: 1ecbd72b-4592-44be-88e7-c0d2d0a790c1"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235
```

workaround is to remove objects manually from Amazon account. I'd be happy to get clean up automatically.

**Comment by a-hilaly** [comment] 2024-03-07 00:44
Fixed by properly waiting for nodegroups to be deleted https://github.com/aws-controllers-k8s/eks-controller/blame/main/test/e2e/tests/test_nodegroup.py#L94
/close

**Closed by a-hilaly** 2024-03-07 00:44 UTC
Labels: kind/bug, priority/important-soon, lifecycle/frozen, area/prow, service/eks
