### ISSUE TITLE
serverlessV2ScalingConfiguration state not changing  

### ISSUE THREAD

**Issue by cdaveaws** [aws-controllers-k8s/community#1373] opened 2022-06-28 19:38 UTC
**Describe the bug**
any changes to serverlessV2ScalingConfiguration is not applied to the cluster.

**Steps to reproduce**

```
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBCluster

metadata:
  name: tfc-db
  namespace: mydb

spec:
  backupRetentionPeriod: 1
  serverlessV2ScalingConfiguration:
    maxCapacity: 16
    minCapacity: 4
  dbClusterIdentifier: tfc-db
  dbSubnetGroupName: mydbsubetgroupack
  engine: aurora-postgresql
  engineVersion: "14.3"
  masterUsername: adminer
  masterUserPassword:
    namespace: mydb
    name: postgres-creds
    key: password
  vpcSecurityGroupIDs:
     - {ADD-SecuritygroupID}
```
 
**Expected outcome**
After changing max/min capacity for serverlessV2ScalingConfiguration, it is not reflected on the cluster on a console.

```
kubectl get  dbcluster -n "${APP_NAMESPACE}"  -o=jsonpath='{..spec.serverlessV2ScalingConfiguration}'
{"maxCapacity":8,"minCapacity":2}
```

logs:

**Environment**
```
aws eks   describe-cluster --name eksworkshop-eksctl --query 'cluster.version'
"1.19"
```
* Kubernetes version:
* Using EKS (yes/no), yes: 
* AWS service targeted : RDS

**Comment by brucegucode** [comment] 2022-06-28 21:43
I'm not very familiar with aurora serverless v2 mode, so i'm asking some questions to internal rds team.
At the same time, if you try describe-db-cluster api https://docs.aws.amazon.com/cli/latest/reference/rds/describe-db-clusters.html for your cluster `tfc-db`. is it showing it's serverless v2 cluster ?

**Comment by cdaveaws** [comment] 2022-06-28 22:05
> 

Yes, Aurora cluster and Serverless instance get created just fine. It is when I try to change serverlessV2ScalingConfiguration ( min/max ACU) it doesn't get applied

**Comment by brucegucode** [comment] 2022-07-05 17:36
I'm able to reproduce this issue now. 
I changed the minCapacity from 2 to 1, and here is runtime log, it find the diff `["Spec","ServerlessV2ScalingConfiguration","MinCapacity"]},"A":1,"B":2}]}` but there is no actual update on `ServerlessV2ScalingConfiguration` made. And then runtime thinks it's in sync again, while RDS actual MinCapacity is still 2 and k8s object thinks it's 1 
```
  serverlessV2ScalingConfiguration:
    Max Capacity:     16
    Min Capacity:     1
```


```
1.6570424063464384e+09	DEBUG	ackrt	>> r.updateResource	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7}
1.6570424063464587e+09	INFO	ackrt	desired resource state has changed	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7, "diff": [{"Path":{"Parts":["Spec","Tags"]},"A":[{"key":"services.k8s.aws/controller-version","value":"rds-unknown"},{"key":"services.k8s.aws/namespace","value":"default"}],"B":[{"key":"services.k8s.aws/controller-version","value":"rds-unknown"},{"key":"services.k8s.aws/namespace","value":"default"}]},{"Path":{"Parts":["Spec","ServerlessV2ScalingConfiguration","MinCapacity"]},"A":1,"B":2}]}
1.6570424063464947e+09	DEBUG	ackrt	>>> rm.Update	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7}
1.6570424063465018e+09	DEBUG	ackrt	>>>> rm.customUpdate	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7}
1.6570424064126318e+09	DEBUG	ackrt	>>>>> rm.syncTags	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7}
1.657042406412652e+09	DEBUG	ackrt	adding tags to cluster	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7, "tags": [{"key":"services.k8s.aws/controller-version","value":"rds-unknown"},{"key":"services.k8s.aws/namespace","value":"default"}]}
1.6570424064497225e+09	DEBUG	ackrt	<<<<< rm.syncTags	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7}
1.6570424064497595e+09	DEBUG	ackrt	<<<< rm.customUpdate	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7}
1.6570424064497824e+09	DEBUG	ackrt	<<< rm.Update	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7, "latest": {}}
1.6570424064497967e+09	DEBUG	ackrt	>>> r.patchResourceMetadataAndSpec	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7}
1.6570424064498806e+09	DEBUG	ackrt	>>>> kc.Patch (metadata + spec)	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7}
1.6570424064785767e+09	DEBUG	ackrt	<<<< kc.Patch (metadata + spec)	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7}
1.657042406478593e+09	DEBUG	ackrt	patched resource metadata and spec	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7, "latest": {}}
1.6570424064786046e+09	DEBUG	ackrt	<<< r.patchResourceMetadataAndSpec	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7}
1.6570424064786124e+09	INFO	ackrt	updated resource	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7}
1.6570424064786212e+09	DEBUG	ackrt	<< r.updateResource	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7}
1.6570424064786339e+09	DEBUG	ackrt	>> r.lateInitializeResource	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7}
1.6570424064786444e+09	DEBUG	ackrt	>>> rm.LateInitialize	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7}
1.6570424064786522e+09	DEBUG	ackrt	no late initialization required.	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7}
1.6570424064786577e+09	DEBUG	ackrt	<<< rm.LateInitialize	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7}
1.6570424064786646e+09	DEBUG	ackrt	>>> r.patchResourceMetadataAndSpec	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7}
1.6570424064787173e+09	DEBUG	ackrt	no difference found between metadata and spec for desired and latest object.	{"account": "316992738638", "role": "", "region": "us-west-2", "kind": "DBCluster", "namespace": "default", "name": "brucegu-serverless-5", "is_adopted": false, "generation": 7}
```

**Comment by brucegucode** [comment] 2022-07-05 21:19
I'm now able to find the root cause, created pr here https://github.com/aws-controllers-k8s/rds-controller/pull/96

**Comment by brucegucode** [comment] 2022-07-06 23:21
feel free to try with latest commit of rds controller for this setting, should be fixed

**Closed** 2022-07-08 17:21 UTC
Labels: bug, RDS
