### ISSUE TITLE
Add usage examples

### ISSUE THREAD

**Issue by rothgar** [aws-controllers-k8s/community#71] opened 2020-06-26 21:30 UTC
It would be great to have examples of how to create services using tools like [cdk8s](https://github.com/awslabs/cdk8s) and [Terraform kubernetes provider](https://www.terraform.io/docs/providers/kubernetes/index.html)

Something that can be integrated into existing projects as dependencies and not raw kubernetes yaml files. :+1:

**Comment by RedbackThomson** [comment] 2021-08-06 01:28
Duplicate of https://github.com/aws-controllers-k8s/community/issues/560

**Closed by RedbackThomson** 2021-08-06 01:28 UTC
Labels: documentation, enhancement
