### ISSUE TITLE
DBParameterGroup doesn't have the requested parameter value

### ISSUE THREAD

**Issue by jamesseo-alation** [aws-controllers-k8s/community#1086] opened 2021-12-06 17:13 UTC
**What is the URL of the document?**

**Which section(s) is the issue in?**

**What needs fixing?**

**Additional context**
I am currently trying to create the below DBParameterGroup. It can create james-rds-parametergroup-test, but when I check rds.logical_replication in AWS console, it doesn't have 1, but 0 (default value). Could you share exact example to create the parameter group w/ custom parameters?
```
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBParameterGroup
metadata:
  name: james-rds-parametergroup-test
spec:
  name: james-rds-parametergroup-test
  description: Test parameter group for ACK
  family: postgres13
  parameters:
    - parameterName: rds.logical_replication
      parameterValue: "1"
```

**Comment by jaypipes** [comment] 2021-12-06 21:09
Hi @jamesseo-alation! Unfortunately, this is a known issue (see #869) :( I'm trying to figure out a clean solution to this...

**Comment by jaypipes** [comment] 2022-05-11 14:24
This is a duplicate of #869

**Closed by jaypipes** 2022-05-11 14:24 UTC
Labels: documentation
